server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    lease-expiration-duration-in-seconds: 2  # wait up hearbeat for microservices up to 2 sec
